# Generated by Django 3.2.9 on 2021-11-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0011_remove_donorregister_last_donate_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorregister',
            name='near_hospital',
        ),
        migrations.AddField(
            model_name='donorregister',
            name='student_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='donorregister',
            name='phone_number',
            field=models.CharField(default='+880', max_length=14),
        ),
        migrations.DeleteModel(
            name='Hospital',
        ),
    ]
